# Generated by Django 6.0.2 on 2026-03-06 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0003_favorito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inmueble',
            name='imagen_url',
        ),
        migrations.AddField(
            model_name='inmueble',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='inmuebles/'),
        ),
    ]
