# Generated by Django 6.0.2 on 2026-03-09 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0006_contacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='InmuebleImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='galeria/')),
                ('inmueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='inmuebles.inmueble')),
            ],
        ),
        migrations.DeleteModel(
            name='ImagenInmueble',
        ),
    ]
