# Generated by Django 5.2.8 on 2026-03-12 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0008_alter_contacto_id_alter_favorito_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='estado',
            field=models.CharField(default='disponible', max_length=20),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='tipo',
            field=models.CharField(choices=[('apartamento', 'Apartamento (2% comisión)'), ('casa', 'Casa (3% comisión)'), ('finca', 'Finca (4% comisión)')], max_length=20),
        ),
    ]
