# Generated by Django 5.2.8 on 2026-03-12 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='estado',
            field=models.CharField(default='disponible', max_length=20),
        ),
    ]
