# Generated by Django 6.0.2 on 2026-03-03 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contactos', '0001_initial'),
        ('inmuebles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='inmueble',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='inmuebles.inmueble'),
        ),
    ]
